# Generated by Django 2.1.4 on 2019-03-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('presentation', models.CharField(max_length=3)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='typeOfMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='typeOfPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='typeMedication',
            field=models.ManyToManyField(to='medicamentos.typeOfMedication'),
        ),
        migrations.AddField(
            model_name='medication',
            name='typePresentation',
            field=models.ManyToManyField(to='medicamentos.typeOfPresentation'),
        ),
    ]
