# Generated by Django 2.1.4 on 2019-03-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='tipo',
        ),
    ]
