# Generated by Django 2.1.4 on 2019-03-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_auto_20190319_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeofmedication',
            old_name='Type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='typeofpresentation',
            old_name='Type',
            new_name='name',
        ),
    ]
