# Generated by Django 2.1.4 on 2019-03-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0003_auto_20190319_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
