# Generated by Django 2.1.4 on 2019-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0004_medication_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='typePresentation',
            field=models.ManyToManyField(blank=True, null=True, to='medicamentos.typeOfPresentation'),
        ),
    ]
