# Generated by Django 2.1.4 on 2019-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0006_tipoventa_ventasmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmes',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ventasmes',
            name='nombre',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='ventasmes',
            name='tipo',
            field=models.ManyToManyField(blank=True, null=True, to='medicamentos.TipoVenta'),
        ),
    ]
