# Generated by Django 2.1.4 on 2019-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0007_auto_20190320_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmes',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ventasmes',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
