# Generated by Django 2.1.4 on 2019-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0008_auto_20190320_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasmes',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
