# Generated by Django 2.1.4 on 2019-03-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0009_auto_20190320_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformedeConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ventaexterna', models.IntegerField()),
                ('valorE', models.FloatField()),
                ('ventasis', models.IntegerField()),
                ('valorS', models.FloatField()),
                ('totalsalida', models.IntegerField()),
                ('saldoDisponible', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ventasmes',
            name='nombre',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ventasmes',
            name='tipo',
            field=models.ManyToManyField(to='medicamentos.TipoVenta'),
        ),
    ]
