# Generated by Django 2.1.4 on 2019-03-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0011_auto_20190320_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='saldoDisponible',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='totalsalida',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='valorE',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='valorS',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='ventaexterna',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='ventasis',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='informedeconsumo',
            name='nombre',
            field=models.CharField(blank=True, default='nombre', max_length=80, null=True),
        ),
    ]
