# Generated by Django 2.1.4 on 2019-03-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0012_auto_20190320_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformedeConsumo',
        ),
        migrations.AddField(
            model_name='medication',
            name='ingreso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
