# Generated by Django 2.1.4 on 2019-03-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0014_auto_20190321_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='typePresentation',
        ),
        migrations.AddField(
            model_name='medication',
            name='typePresentation',
            field=models.ManyToManyField(blank=True, null=True, to='medicamentos.typeOfPresentation'),
        ),
    ]
