# Generated by Django 2.1.4 on 2019-03-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0015_auto_20190321_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='typeMedication',
            field=models.ManyToManyField(blank=True, null=True, to='medicamentos.typeOfMedication'),
        ),
    ]
