# Generated by Django 2.1.4 on 2019-03-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0018_auto_20190321_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventasmes',
            name='tipo',
        ),
        migrations.AddField(
            model_name='ventasmes',
            name='tipo',
            field=models.ManyToManyField(blank=True, null=True, to='medicamentos.TipoVenta'),
        ),
    ]
