# Generated by Django 2.1.4 on 2019-03-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0019_auto_20190321_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='exo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='fecha_expedicion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='int_sanitaria',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='transferencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
