# Generated by Django 2.1.4 on 2019-03-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0020_auto_20190323_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='fecha_expedicion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
