# Generated by Django 2.1.4 on 2019-03-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0021_auto_20190323_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='disponible_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
