# Generated by Django 2.1.4 on 2019-03-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0022_medication_disponible_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='disponible_actual',
        ),
    ]
